import {
  defaultBlockTexts,
  InvitationDraft,
  InvitationLocation,
  InvitationMedia,
  InvitationSectionKey,
  InvitationTheme
} from "@/lib/draft-storage";
import { createClient } from "@/lib/supabase/client";

type SaveResult = { status: "remote"; message: string } | { status: "local"; message: string } | { status: "error"; message: string };
type UploadResult = { status: "remote"; url: string; message: string } | { status: "error"; message: string };

const sectionToDb: Record<InvitationSectionKey, string> = { countdown:"countdown", ceremony:"ceremony", reception:"reception", rsvp:"rsvp", gallery:"gallery", video:"video", program:"program", dressCode:"dress_code", giftInfo:"gift_info" };
const dbToSection: Record<string, InvitationSectionKey> = { countdown:"countdown", ceremony:"ceremony", reception:"reception", rsvp:"rsvp", gallery:"gallery", video:"video", program:"program", dress_code:"dressCode", gift_info:"giftInfo" };
function isoDateOrNull(value:string){return /^\d{4}-\d{2}-\d{2}$/.test(value)?value:null;}
function timeOrNull(value:string){return /^\d{2}:\d{2}(:\d{2})?$/.test(value)?value:null;}
function themeWithDisplayDate(draft:InvitationDraft){return{...draft.theme,blockTexts:{...defaultBlockTexts,...(draft.blockTexts??{})},eventDateLabel:draft.eventDate,eventTimeLabel:draft.eventTime};}
function readDisplayTheme(value:unknown){if(value&&typeof value==="object")return value as Partial<InvitationTheme>&{blockTexts?:Partial<Record<InvitationSectionKey,string>>;eventDateLabel?:string;eventTimeLabel?:string;};return{};}
function rowToDraft(row:any):InvitationDraft{const content=Array.isArray(row.invitation_content)?row.invitation_content[0]:row.invitation_content;const themeRow=Array.isArray(row.invitation_themes)?row.invitation_themes[0]:row.invitation_themes;const d=readDisplayTheme(content?.theme);const theme:InvitationTheme={template:(themeRow?.template_slug??d.template??"darkLuxury") as InvitationTheme["template"],primaryColor:themeRow?.primary_color??d.primaryColor??"#151313",accentColor:themeRow?.accent_color??d.accentColor??"#b87333",fontStyle:(themeRow?.font_style??d.fontStyle??"serif") as InvitationTheme["fontStyle"],backgroundImage:d.backgroundImage,backgroundVideo:d.backgroundVideo,textColor:d.textColor,buttonColor:d.buttonColor,buttonTextColor:d.buttonTextColor,fontScale:typeof d.fontScale==="number"?d.fontScale:undefined,titleFontScale:typeof d.titleFontScale==="number"?d.titleFontScale:undefined,textFontScale:typeof d.textFontScale==="number"?d.textFontScale:undefined,coverElement:d.coverElement,coverLogoUrl:d.coverLogoUrl,coverLogoScale:typeof d.coverLogoScale==="number"?d.coverLogoScale:undefined};const locations:InvitationLocation[]=(row.invitation_locations??[]).map((x:any)=>({id:x.id,type:x.type,name:x.name??"",address:x.address??"",description:x.description??"",mapsUrl:x.maps_url??"",enabled:x.enabled??true,imageUrl:x.image_url??""}));const media:InvitationMedia[]=(row.invitation_media??[]).map((x:any)=>({id:x.id,type:x.type,title:x.title??"",url:x.external_url??x.storage_path??""}));const activeSections=(row.invitation_sections??[]).filter((x:any)=>x.enabled).sort((a:any,b:any)=>a.sort_order-b.sort_order).map((x:any)=>dbToSection[x.type]).filter(Boolean);return{id:row.id,slug:row.slug,status:row.status==="published"?"published":"draft",title:row.title,subtitle:row.subtitle??"",hostName:row.host_name??"",eventDate:d.eventDateLabel??row.event_date??"",eventTime:d.eventTimeLabel??row.event_time?.slice(0,5)??"",whatsappNumber:row.whatsapp_number??"",story:content?.story??"",dressCode:content?.dress_code??"",giftIban:content?.gift_iban??"",giftWishes:Array.isArray(content?.gift_wishes)?content.gift_wishes.map((w:any,i:number)=>({id:w.id??`wish-${i+1}`,title:w.title??""})):[],program:Array.isArray(content?.program)?content.program.map((x:any,i:number)=>({id:x.id??`program-${i+1}`,time:x.time??"",description:x.description??""})):[],blockTexts:{...defaultBlockTexts,...(d.blockTexts??{})},activeSections,locations,media,theme,updatedAt:row.updated_at};}

export async function getCurrentUser(){const s=createClient();if(!s)return null;const{data}=await s.auth.getUser();return data.user;}
export async function signInWithEmail(email:string){const s=createClient();if(!s)return{error:{message:"Supabase non e configurato."}};return s.auth.signInWithOtp({email,options:{shouldCreateUser:false,emailRedirectTo:`${window.location.origin}/dashboard`}});}
export async function registerWithEmailPassword(fullName:string,email:string,password:string){const s=createClient();if(!s)return{error:{message:"Supabase non e configurato."}};return s.auth.signUp({email,password,options:{data:{full_name:fullName},emailRedirectTo:`${window.location.origin}/account-attivo`}});}
export async function loginWithEmailPassword(email:string,password:string){const s=createClient();if(!s)return{error:{message:"Supabase non e configurato."}};return s.auth.signInWithPassword({email,password});}
export async function signOut(){const s=createClient();if(s)await s.auth.signOut();}

async function uploadImageToLocationBucket(file:File,path:string):Promise<UploadResult>{const s=createClient();if(!s)return{status:"error",message:"Supabase non è configurato."};if(!["image/jpeg","image/png","image/webp"].includes(file.type))return{status:"error",message:"Carica un'immagine JPG, PNG o WebP."};if(file.size>8*1024*1024)return{status:"error",message:"L'immagine non può superare 8 MB."};const{data:u}=await s.auth.getUser();if(!u.user)return{status:"error",message:"Accedi prima di caricare l'immagine."};const{error}=await s.storage.from("invitation-location-images").upload(path,file,{cacheControl:"3600",upsert:false,contentType:file.type});if(error)return{status:"error",message:error.message};const{data}=s.storage.from("invitation-location-images").getPublicUrl(path);return{status:"remote",url:data.publicUrl,message:"Immagine caricata."};}
export async function uploadLocationImage(draftId:string,locationId:string,file:File):Promise<UploadResult>{const ext=file.name.split(".").pop()?.toLowerCase().replace(/[^a-z0-9]/g,"")||"jpg";const s=createClient();if(!s)return{status:"error",message:"Supabase non è configurato."};const{data:u}=await s.auth.getUser();if(!u.user)return{status:"error",message:"Accedi prima di caricare la foto."};return uploadImageToLocationBucket(file,`${u.user.id}/${draftId}/${locationId}-${Date.now()}.${ext}`);}
export async function uploadCoverLogo(draftId:string,file:File):Promise<UploadResult>{const s=createClient();if(!s)return{status:"error",message:"Supabase non è configurato."};const{data:u}=await s.auth.getUser();if(!u.user)return{status:"error",message:"Accedi prima di caricare il logo."};const ext=file.name.split(".").pop()?.toLowerCase().replace(/[^a-z0-9]/g,"")||"png";return uploadImageToLocationBucket(file,`${u.user.id}/${draftId}/cover-logo-${Date.now()}.${ext}`);}
export async function uploadInvitationMedia(draftId:string,file:File):Promise<UploadResult>{const s=createClient();if(!s)return{status:"error",message:"Supabase non è configurato."};const photo=["image/jpeg","image/png","image/webp"].includes(file.type),video=["video/mp4","video/quicktime","video/webm"].includes(file.type);if(!photo&&!video)return{status:"error",message:"Carica una foto JPG, PNG o WebP oppure un video compatibile."};if(file.size>50*1024*1024)return{status:"error",message:"Il file non può superare 50 MB."};const{data:u}=await s.auth.getUser();if(!u.user)return{status:"error",message:"Accedi prima di aggiungere contenuti Social all'invito."};const ext=file.name.split(".").pop()?.toLowerCase().replace(/[^a-z0-9]/g,"")||(photo?"jpg":"mp4");const path=`${draftId}/owner/${crypto.randomUUID()}.${ext}`,bucket="invitation-guest-media";const{error}=await s.storage.from(bucket).upload(path,file,{cacheControl:"3600",upsert:false});if(error)return{status:"error",message:error.message};const{data}=s.storage.from(bucket).getPublicUrl(path);return{status:"remote",url:data.publicUrl,message:"Contenuto Social caricato. Salva la bozza per pubblicarlo."};}
export async function uploadCustomTemplateImage(file:File):Promise<UploadResult>{const s=createClient();if(!s)return{status:"error",message:"Supabase non è configurato."};const{data:u}=await s.auth.getUser();if(!u.user)return{status:"error",message:"Accedi prima di caricare la grafica."};const ext=file.name.split(".").pop()?.toLowerCase().replace(/[^a-z0-9]/g,"")||"jpg";return uploadImageToLocationBucket(file,`${u.user.id}/custom-templates/template-${Date.now()}.${ext}`);}

export async function saveDraftToSupabase(draft:InvitationDraft):Promise<SaveResult>{const s=createClient();if(!s)return{status:"local",message:"Bozza salvata solo su questo dispositivo."};const{data:u}=await s.auth.getUser();if(!u.user)return{status:"local",message:"Accedi per sincronizzare la bozza."};const slug=draft.slug;const{error:invError}=await s.from("invitations").upsert({id:draft.id,user_id:u.user.id,slug,status:draft.status,title:draft.title,subtitle:draft.subtitle,host_name:draft.hostName,event_date:isoDateOrNull(draft.eventDate),event_time:timeOrNull(draft.eventTime),whatsapp_number:draft.whatsappNumber,updated_at:new Date().toISOString()});if(invError)return{status:"error",message:invError.message};const{error:contentError}=await s.from("invitation_content").upsert({invitation_id:draft.id,story:draft.story,dress_code:draft.dressCode,gift_iban:draft.giftIban,gift_wishes:draft.giftWishes,program:draft.program,theme:themeWithDisplayDate(draft),updated_at:new Date().toISOString()},{onConflict:"invitation_id"});if(contentError)return{status:"error",message:contentError.message};await s.from("invitation_themes").upsert({invitation_id:draft.id,template_slug:draft.theme.template,primary_color:draft.theme.primaryColor,accent_color:draft.theme.accentColor,font_style:draft.theme.fontStyle},{onConflict:"invitation_id"});await s.from("invitation_sections").delete().eq("invitation_id",draft.id);if(draft.activeSections.length)await s.from("invitation_sections").insert(draft.activeSections.map((section,index)=>({invitation_id:draft.id,type:sectionToDb[section],enabled:true,sort_order:index})));await s.from("invitation_locations").delete().eq("invitation_id",draft.id);if(draft.locations.length)await s.from("invitation_locations").insert(draft.locations.map(l=>({id:l.id,invitation_id:draft.id,type:l.type,name:l.name,address:l.address,description:l.description,maps_url:l.mapsUrl,enabled:l.enabled,image_url:l.imageUrl})));await s.from("invitation_media").delete().eq("invitation_id",draft.id);if(draft.media.length)await s.from("invitation_media").insert(draft.media.filter(m=>m.url&&!m.url.startsWith("blob:")).map(m=>({id:m.id,invitation_id:draft.id,type:m.type,title:m.title,external_url:m.url})));return{status:"remote",message:"Bozza sincronizzata online."};}
async function fetchDraftQuery(s:any){return s.from("invitations").select(`*, invitation_content(*), invitation_themes(*), invitation_sections(*), invitation_locations(*), invitation_media(*)`);}
export async function fetchDraftsFromSupabase(){const s=createClient();if(!s)return[];const{data}=await(await fetchDraftQuery(s)).order("updated_at",{ascending:false});return(data??[]).map(rowToDraft);}
export async function findDraftBySlugFromSupabase(slug:string){const s=createClient();if(!s)return null;const{data}=await(await fetchDraftQuery(s)).eq("slug",slug).maybeSingle();return data?rowToDraft(data):null;}
