import {
  defaultBlockTexts,
  InvitationDraft,
  InvitationLocation,
  InvitationMedia,
  InvitationSectionKey,
  InvitationTheme
} from "@/lib/draft-storage";
import { createClient } from "@/lib/supabase/client";

type SaveResult = { status: "remote"; message: string } | { status: "local"; message: string } | { status: "error"; message: string };
type UploadResult = { status: "remote"; url: string; message: string } | { status: "error"; message: string };

const sectionToDb: Record<InvitationSectionKey, string> = { countdown:"countdown", ceremony:"ceremony", reception:"reception", rsvp:"rsvp", gallery:"gallery", video:"video", program:"program", dressCode:"dress_code", giftInfo:"gift_info" };
const dbToSection: Record<string, InvitationSectionKey> = { countdown:"countdown", ceremony:"ceremony", reception:"reception", rsvp:"rsvp", gallery:"gallery", video:"video", program:"program", dress_code:"dressCode", gift_info:"giftInfo" };
function isoDateOrNull(value:string){return /^\d{4}-\d{2}-\d{2}$/.test(value)?value:null;}
function timeOrNull(value:string){return /^\d{2}:\d{2}(:\d{2})?$/.test(value)?value:null;}
function themeWithDisplayDate(draft:InvitationDraft){return {...draft.theme,blockTexts:{...defaultBlockTexts,...(draft.blockTexts??{})},eventDateLabel:draft.eventDate,eventTimeLabel:draft.eventTime};}
function readDisplayTheme(value:unknown){if(value&&typeof value==="object")return value as Partial<InvitationTheme>&{blockTexts?:Partial<Record<InvitationSectionKey,string>>;eventDateLabel?:string;eventTimeLabel?:string};return {};}
function rowToDraft(row:any):InvitationDraft{
 const content=Array.isArray(row.invitation_content)?row.invitation_content[0]:row.invitation_content;const themeRow=Array.isArray(row.invitation_themes)?row.invitation_themes[0]:row.invitation_themes;const d=readDisplayTheme(content?.theme);
 const theme:InvitationTheme={template:(themeRow?.template_slug??d.template??"darkLuxury") as InvitationTheme["template"],primaryColor:themeRow?.primary_color??d.primaryColor??"#151313",accentColor:themeRow?.accent_color??d.accentColor??"#b87333",fontStyle:(themeRow?.font_style??d.fontStyle??"serif") as InvitationTheme["fontStyle"],backgroundImage:d.backgroundImage,backgroundVideo:d.backgroundVideo,textColor:d.textColor,buttonColor:d.buttonColor,buttonTextColor:d.buttonTextColor,fontScale:typeof d.fontScale==="number"?d.fontScale:undefined,titleFontScale:typeof d.titleFontScale==="number"?d.titleFontScale:undefined,textFontScale:typeof d.textFontScale==="number"?d.textFontScale:undefined,coverElement:d.coverElement,coverLogoUrl:d.coverLogoUrl,coverLogoScale:typeof d.coverLogoScale==="number"?d.coverLogoScale:undefined,countdownStyle:d.countdownStyle,heroMetaStyle:d.heroMetaStyle};
 const locations:InvitationLocation[]=(row.invitation_locations??[]).map((l:any)=>({id:l.id,type:l.type,name:l.name??"",address:l.address??"",description:l.description??"",mapsUrl:l.maps_url??"",enabled:l.enabled??true,imageUrl:l.image_url??""}));
 const media:InvitationMedia[]=(row.invitation_media??[]).map((i:any)=>({id:i.id,type:i.type,title:i.title??"",url:i.external_url??i.storage_path??""}));
 const activeSections=(row.invitation_sections??[]).filter((s:any)=>s.enabled).sort((a:any,b:any)=>a.sort_order-b.sort_order).map((s:any)=>dbToSection[s.type]).filter(Boolean);
 return {id:row.id,slug:row.slug,status:row.status==="published"?"published":"draft",title:row.title,subtitle:row.subtitle??"",hostName:row.host_name??"",eventDate:d.eventDateLabel??row.event_date??"",eventTime:d.eventTimeLabel??row.event_time?.slice(0,5)??"",whatsappNumber:row.whatsapp_number??"",story:content?.story??"",dressCode:content?.dress_code??"",giftIban:content?.gift_iban??"",giftWishes:Array.isArray(content?.gift_wishes)?content.gift_wishes.map((w:any,index:number)=>({id:w.id??`wish-${index+1}`,title:w.title??""})):[],program:Array.isArray(content?.program)?content.program.map((i:any,index:number)=>({id:i.id??`program-${index+1}`,time:i.time??"",description:i.description??""})):[],blockTexts:{...defaultBlockTexts,...(d.blockTexts??{})},activeSections,locations,media,theme,updatedAt:row.updated_at};
}
export async function getCurrentUser(){const s=createClient();if(!s)return null;const{data}=await s.auth.getUser();return data.user;}
export async function saveDraftToSupabase(draft:InvitationDraft):Promise<SaveResult>{const s=createClient();if(!s)return{status:"local",message:"Bozza salvata sul dispositivo."};const user=await getCurrentUser();if(!user)return{status:"local",message:"Bozza salvata sul dispositivo. Accedi per sincronizzarla online."};const invitation={id:draft.id,user_id:user.id,slug:draft.slug,status:draft.status,title:draft.title,subtitle:draft.subtitle,host_name:draft.hostName,event_date:isoDateOrNull(draft.eventDate),event_time:timeOrNull(draft.eventTime),whatsapp_number:draft.whatsappNumber,updated_at:new Date().toISOString()};const{error}=await s.from("invitations").upsert(invitation);if(error)return{status:"error",message:error.message};await s.from("invitation_content").upsert({invitation_id:draft.id,story:draft.story,dress_code:draft.dressCode,gift_iban:draft.giftIban,gift_wishes:draft.giftWishes,program:draft.program,theme:themeWithDisplayDate(draft)});await s.from("invitation_themes").upsert({invitation_id:draft.id,template_slug:draft.theme.template,primary_color:draft.theme.primaryColor,accent_color:draft.theme.accentColor,font_style:draft.theme.fontStyle});await s.from("invitation_sections").delete().eq("invitation_id",draft.id);if(draft.activeSections.length)await s.from("invitation_sections").insert(draft.activeSections.map((section,index)=>({invitation_id:draft.id,type:sectionToDb[section],sort_order:index,enabled:true})));return{status:"remote",message:"Bozza sincronizzata online."};}
export async function findDraftBySlugFromSupabase(slug:string){const s=createClient();if(!s)return null;const{data}=await s.from("invitations").select("*, invitation_content(*), invitation_themes(*), invitation_sections(*), invitation_locations(*), invitation_media(*)").eq("slug",slug).maybeSingle();return data?rowToDraft(data):null;}
export async function uploadInvitationMedia(file:File,invitationId:string,mediaId:string){const s=createClient();if(!s)return{status:"error",message:"Storage non disponibile."} as UploadResult;const ext=file.name.split(".").pop()||"bin";const path=`${invitationId}/${mediaId}.${ext}`;const{error}=await s.storage.from("invitation-media").upload(path,file,{upsert:true});if(error)return{status:"error",message:error.message};const{data}=s.storage.from("invitation-media").getPublicUrl(path);return{status:"remote",url:data.publicUrl,message:"Media caricato."} as UploadResult;}
export async function uploadLocationImage(file:File,invitationId:string,locationId:string){return uploadInvitationMedia(file,invitationId,`location-${locationId}`);}
