import {
  defaultBlockTexts,
  InvitationDraft,
  InvitationLocation,
  InvitationMedia,
  InvitationSectionKey,
  InvitationTheme
} from "@/lib/draft-storage";
import { createClient } from "@/lib/supabase/client";

type SaveResult = { status: "remote" | "local" | "error"; message: string };
type UploadResult = { status: "remote"; url: string; message: string } | { status: "error"; message: string };
const sectionToDb:Record<InvitationSectionKey,string>={countdown:"countdown",ceremony:"ceremony",reception:"reception",rsvp:"rsvp",gallery:"gallery",video:"video",program:"program",dressCode:"dress_code",giftInfo:"gift_info"};
const dbToSection:Record<string,InvitationSectionKey>={countdown:"countdown",ceremony:"ceremony",reception:"reception",rsvp:"rsvp",gallery:"gallery",video:"video",program:"program",dress_code:"dressCode",gift_info:"giftInfo"};
function isoDateOrNull(v:string){return /^\d{4}-\d{2}-\d{2}$/.test(v)?v:null}function timeOrNull(v:string){return /^\d{2}:\d{2}(:\d{2})?$/.test(v)?v:null}
function themeWithDisplayDate(d:InvitationDraft){return{...d.theme,blockTexts:{...defaultBlockTexts,...(d.blockTexts??{})},eventDateLabel:d.eventDate,eventTimeLabel:d.eventTime}}
function readDisplayTheme(v:unknown){return v&&typeof v==="object"?v as Partial<InvitationTheme>&{blockTexts?:Partial<Record<InvitationSectionKey,string>>;eventDateLabel?:string;eventTimeLabel?:string}:{};}
function rowToDraft(row:any):InvitationDraft{const content=Array.isArray(row.invitation_content)?row.invitation_content[0]:row.invitation_content;const tr=Array.isArray(row.invitation_themes)?row.invitation_themes[0]:row.invitation_themes;const dt=readDisplayTheme(content?.theme);const theme:InvitationTheme={template:(tr?.template_slug??dt.template??"darkLuxury") as InvitationTheme["template"],primaryColor:tr?.primary_color??dt.primaryColor??"#151313",accentColor:tr?.accent_color??dt.accentColor??"#b87333",fontStyle:(dt.fontStyle??tr?.font_style??"serif") as InvitationTheme["fontStyle"],backgroundImage:dt.backgroundImage,backgroundVideo:dt.backgroundVideo,textColor:dt.textColor,buttonColor:dt.buttonColor,buttonTextColor:dt.buttonTextColor,fontScale:typeof dt.fontScale==="number"?dt.fontScale:undefined,titleFontScale:typeof dt.titleFontScale==="number"?dt.titleFontScale:undefined,textFontScale:typeof dt.textFontScale==="number"?dt.textFontScale:undefined,heroTitleScale:typeof dt.heroTitleScale==="number"?dt.heroTitleScale:undefined,heroMetaScale:typeof dt.heroMetaScale==="number"?dt.heroMetaScale:undefined,coverElement:dt.coverElement,coverLogoUrl:dt.coverLogoUrl,coverLogoScale:typeof dt.coverLogoScale==="number"?dt.coverLogoScale:undefined,coverNumberScale:typeof dt.coverNumberScale==="number"?dt.coverNumberScale:undefined,coverText:dt.coverText,coverTextScale:typeof dt.coverTextScale==="number"?dt.coverTextScale:undefined,countdownStyle:dt.countdownStyle,heroMetaStyle:dt.heroMetaStyle};
const locations:InvitationLocation[]=(row.invitation_locations??[]).map((l:any)=>({id:l.id,type:l.type,name:l.name??"",address:l.address??"",description:l.description??"",mapsUrl:l.maps_url??"",enabled:l.enabled??true,imageUrl:l.image_url??""}));const media:InvitationMedia[]=(row.invitation_media??[]).map((i:any)=>({id:i.id,type:i.type,title:i.title??"",url:i.external_url??i.storage_path??""}));const activeSections=(row.invitation_sections??[]).filter((s:any)=>s.enabled).sort((a:any,b:any)=>a.sort_order-b.sort_order).map((s:any)=>dbToSection[s.type]).filter(Boolean);
return{id:row.id,slug:row.slug,status:row.status==="published"?"published":"draft",title:row.title,subtitle:row.subtitle??"",hostName:row.host_name??"",eventDate:dt.eventDateLabel??row.event_date??"",eventTime:dt.eventTimeLabel??row.event_time?.slice(0,5)??"",whatsappNumber:row.whatsapp_number??"",story:content?.story??"",dressCode:content?.dress_code??"",giftIban:content?.gift_iban??"",giftWishes:Array.isArray(content?.gift_wishes)?content.gift_wishes.map((w:any,i:number)=>({id:w.id??`wish-${i+1}`,title:w.title??""})):[],program:Array.isArray(content?.program)?content.program.map((i:any,x:number)=>({id:i.id??`program-${x+1}`,time:i.time??"",description:i.description??""})):[],blockTexts:{...defaultBlockTexts,...(dt.blockTexts??{})},activeSections,locations,media,theme,updatedAt:row.updated_at};}
export async function getCurrentUser(){const s=createClient();if(!s)return null;const{data}=await s.auth.getUser();return data.user}export async function signInWithEmail(email:string){const s=createClient();if(!s)return{error:{message:"Supabase non e configurato."}};return s.auth.signInWithOtp({email,options:{shouldCreateUser:false,emailRedirectTo:`${window.location.origin}/dashboard`}})}export async function registerWithEmailPassword(fullName:string,email:string,password:string){const s=createClient();if(!s)return{error:{message:"Supabase non e configurato."}};return s.auth.signUp({email,password,options:{data:{full_name:fullName},emailRedirectTo:`${window.location.origin}/account-attivo`}})}export async function loginWithEmailPassword(email:string,password:string){const s=createClient();if(!s)return{error:{message:"Supabase non e configurato."}};return s.auth.signInWithPassword({email,password})}export async function signOut(){const s=createClient();if(s)await s.auth.signOut()}
async function uploadImageToLocationBucket(file:File,path:string):Promise<UploadResult>{const s=createClient();if(!s)return{status:"error",message:"Supabase non è configurato."};if(!["image/jpeg","image/png","image/webp"].includes(file.type))return{status:"error",message:"Carica un'immagine JPG, PNG o WebP."};if(file.size>8*1024*1024)return{status:"error",message:"L'immagine non può superare 8 MB."};const{data:u}=await s.auth.getUser();if(!u.user)return{status:"error",message:"Accedi prima di caricare l'immagine."};const{error}=await s.storage.from("invitation-location-images").upload(path,file,{cacheControl:"3600",upsert:false,contentType:file.type});if(error)return{status:"error",message:error.message};const{data}=s.storage.from("invitation-location-images").getPublicUrl(path);return{status:"remote",url:data.publicUrl,message:"Immagine caricata."}}
export async function uploadLocationImage(draftId:string,locationId:string,file:File){const s=createClient();if(!s)return{status:"error" as const,message:"Supabase non è configurato."};const{data:u}=await s.auth.getUser();if(!u.user)return{status:"error" as const,message:"Accedi prima di caricare la foto."};const e=file.name.split(".").pop()?.toLowerCase().replace(/[^a-z0-9]/g,"")||"jpg";return uploadImageToLocationBucket(file,`${u.user.id}/${draftId}/${locationId}-${Date.now()}.${e}`)}export async function uploadCoverLogo(draftId:string,file:File){const s=createClient();if(!s)return{status:"error" as const,message:"Supabase non è configurato."};const{data:u}=await s.auth.getUser();if(!u.user)return{status:"error" as const,message:"Accedi prima di caricare il logo."};const e=file.name.split(".").pop()?.toLowerCase().replace(/[^a-z0-9]/g,"")||"png";return uploadImageToLocationBucket(file,`${u.user.id}/${draftId}/cover-logo-${Date.now()}.${e}`)}
export async function uploadInvitationMedia(draftId:string,file:File):Promise<UploadResult>{const s=createClient();if(!s)return{status:"error",message:"Supabase non è configurato."};const photo=["image/jpeg","image/png","image/webp"].includes(file.type),video=["video/mp4","video/quicktime","video/webm"].includes(file.type);if(!photo&&!video)return{status:"error",message:"Carica una foto JPG, PNG o WebP oppure un video compatibile."};if(file.size>50*1024*1024)return{status:"error",message:"Il file non può superare 50 MB."};const{data:u}=await s.auth.getUser();if(!u.user)return{status:"error",message:"Accedi prima di aggiungere contenuti Social all'invito."};const e=file.name.split(".").pop()?.toLowerCase().replace(/[^a-z0-9]/g,"")||(photo?"jpg":"mp4"),path=`${draftId}/owner/${crypto.randomUUID()}.${e}`,bucket="invitation-guest-media";const{error}=await s.storage.from(bucket).upload(path,file,{cacheControl:"3600",upsert:false});if(error)return{status:"error",message:error.message};const{data}=s.storage.from(bucket).getPublicUrl(path);return{status:"remote",url:data.publicUrl,message:"Contenuto Social caricato. Salva la bozza per pubblicarlo."}}
export async function uploadCustomTemplateImage(file:File){const s=createClient();if(!s)return{status:"error" as const,message:"Supabase non è configurato."};const{data:u}=await s.auth.getUser();if(!u.user)return{status:"error" as const,message:"Accedi prima di caricare la grafica."};const e=file.name.split(".").pop()?.toLowerCase().replace(/[^a-z0-9]/g,"")||"jpg";return uploadImageToLocationBucket(file,`${u.user.id}/custom-templates/template-${Date.now()}.${e}`)}
export async function saveDraftToSupabase(draft:InvitationDraft):Promise<SaveResult>{const s=createClient();if(!s)return{status:"local",message:"Bozza salvata nel browser. Configura Supabase per il salvataggio account."};const{data:u,error:ue}=await s.auth.getUser();if(ue||!u.user)return{status:"local",message:"Bozza salvata nel browser. Accedi per salvarla anche su Supabase."};const user=u.user;let{error}=await s.from("profiles").upsert({id:user.id,email:user.email,updated_at:new Date().toISOString()});if(error)return{status:"error",message:error.message};({error}=await s.from("invitations").upsert({id:draft.id,owner_id:user.id,slug:draft.slug,status:draft.status,title:draft.title,subtitle:draft.subtitle,host_name:draft.hostName,event_date:isoDateOrNull(draft.eventDate),event_time:timeOrNull(draft.eventTime),venue_name:draft.locations[0]?.name??null,venue_address:draft.locations[0]?.address??null,whatsapp_number:draft.whatsappNumber,updated_at:new Date().toISOString()}));if(error)return{status:"error",message:error.message};({error}=await s.from("invitation_content").upsert({invitation_id:draft.id,story:draft.story,dress_code:draft.dressCode,gift_iban:draft.giftIban||null,gift_wishes:draft.giftWishes,program:draft.program,theme:themeWithDisplayDate(draft),updated_at:new Date().toISOString()}));if(error)return{status:"error",message:error.message};await s.from("invitation_sections").delete().eq("invitation_id",draft.id);await s.from("invitation_locations").delete().eq("invitation_id",draft.id);await s.from("invitation_media").delete().eq("invitation_id",draft.id);if(draft.activeSections.length){({error}=await s.from("invitation_sections").insert(draft.activeSections.map((x,i)=>({invitation_id:draft.id,type:sectionToDb[x],title:x,enabled:true,sort_order:i}))));if(error)return{status:"error",message:error.message}}if(draft.locations.length){({error}=await s.from("invitation_locations").insert(draft.locations.map((l,i)=>({invitation_id:draft.id,type:l.type,name:l.name||"Location",address:l.address,description:l.description,maps_url:l.mapsUrl,enabled:l.enabled,image_url:l.imageUrl||null,sort_order:i}))));if(error)return{status:"error",message:error.message}}const pm=draft.media.filter(i=>/^https?:\/\//.test(i.url));if(pm.length){({error}=await s.from("invitation_media").insert(pm.map((i,x)=>({invitation_id:draft.id,type:i.type,title:i.title,external_url:i.url,sort_order:x}))));if(error)return{status:"error",message:error.message}}({error}=await s.from("invitation_themes").upsert({invitation_id:draft.id,template_slug:draft.theme.template,primary_color:draft.theme.primaryColor,accent_color:draft.theme.accentColor,font_style:draft.theme.fontStyle,updated_at:new Date().toISOString()}));if(error)return{status:"error",message:error.message};return{status:"remote",message:"Bozza salvata su Supabase e nel browser."}}
export async function loadUserDraftsFromSupabase(){const s=createClient();if(!s)return{drafts:[] as InvitationDraft[],message:"Supabase non configurato."};const{data:u}=await s.auth.getUser();if(!u.user)return{drafts:[] as InvitationDraft[],message:"Accedi per vedere le bozze salvate online."};const{data,error}=await s.from("invitations").select("*, invitation_content(*), invitation_themes(*), invitation_locations(*), invitation_sections(*), invitation_media(*)").eq("owner_id",u.user.id).order("updated_at",{ascending:false});return{drafts:error?[]:(data??[]).map(rowToDraft),message:error?error.message:"Bozze sincronizzate con il tuo account."}}
export async function findDraftBySlugFromSupabase(slug:string){const s=createClient();if(!s)return null;const{data,error}=await s.from("invitations").select("*, invitation_content(*), invitation_themes(*), invitation_locations(*), invitation_sections(*), invitation_media(*)").eq("slug",slug).maybeSingle();return error||!data?null:rowToDraft(data)}
export async function deleteDraftFromSupabase(id:string):Promise<SaveResult>{const s=createClient();if(!s)return{status:"error",message:"Supabase non configurato."};const{data:u}=await s.auth.getUser();if(!u.user)return{status:"error",message:"Accedi per eliminare l'invito."};const{error}=await s.from("invitations").delete().eq("id",id).eq("owner_id",u.user.id);return error?{status:"error",message:error.message}:{status:"remote",message:"Invito eliminato definitivamente."}}
