const featuredTemplates = [
  { name: "Rosa Perla", category: "Matrimonio", image: "/templates/rosa-perla.webp" },
  { name: "Dolce Festa", category: "Compleanno", image: "/templates/dolce-festa.webp" },
  { name: "Promessa di Fiori", category: "Battesimo", image: "/templates/promessa-fiori.webp" },
  { name: "Seta Bianca", category: "Comunione", image: "/templates/seta-bianca.webp" },
  { name: "Festa di Colori", category: "Laurea", image: "/templates/festa-colori.webp" },
  { name: "Notte Zaffiro", category: "Evento", image: "/templates/notte-zaffiro.webp" }
];

export default function HomePage() {
  return (
    <main>
      <header className="topbar home-topbar"><a className="brand" href="/">ilmioinvito.com</a><nav className="nav" aria-label="Navigazione principale"><a href="#come-funziona">Come funziona</a><a href="/templates">Template</a><a href="/abbonamenti">Prezzi</a><a href="/login">Accedi</a><a className="home-nav-cta" href="/registrati">Crea il tuo invito</a></nav></header>

      <section className="hero home-hero"><div className="hero-inner home-hero-layout"><div className="hero-copy"><p className="eyebrow">Il tuo evento comincia dall’invito</p><h1>Un invito digitale che racconta la vostra storia.</h1><p className="lead">Scegli la grafica, personalizza ogni dettaglio e condividi un unico link con i tuoi invitati. Conferme, programma, location, foto e informazioni sempre a portata di mano.</p><div className="actions"><a className="button" href="/registrati">Crea il tuo invito</a><a className="button secondary" href="/templates">Scopri i template</a></div><div className="home-trust-row"><span>✓ Creazione gratuita</span><span>✓ Paghi solo alla pubblicazione</span><span>✓ Nessun rinnovo automatico</span></div></div><a className="home-phone-showcase" href="/templates" aria-label="Guarda il template matrimonio Rosa Perla"><div className="home-phone-frame"><div className="home-phone-speaker" /><div className="home-phone-screen"><section className="home-phone-cover"><span>Il nostro matrimonio</span><h2>Sofia<br />& Lorenzo</h2><p>Insieme, per sempre</p><div className="home-phone-date"><b>21</b><span>SETTEMBRE<br />2026</span></div></section><section className="home-phone-preview-content"><p>Ci sposiamo!</p><h3>Condividete con noi questo giorno speciale</h3><div className="home-phone-countdown"><span><b>32</b>Giorni</span><span><b>08</b>Ore</span><span><b>24</b>Minuti</span></div><div className="home-phone-location"><span>La cerimonia</span><strong>Chiesa di Santa Maria</strong><small>Ore 16:30 · Torino</small></div><button type="button">Conferma la partecipazione</button></section></div></div><span className="home-phone-caption">Ecco come vedranno il tuo invito</span></a></div></section>

      <section className="section home-intro"><div className="section-inner home-centered-heading"><p className="eyebrow">Tutto in un solo invito</p><h2>Più elegante di un messaggio.<br />Più semplice di quanto immagini.</h2><p className="muted">ilmioinvito.com trasforma tutte le informazioni del tuo evento in un’esperienza digitale bella da vedere, facile da condividere e semplice da gestire.</p></div><div className="section-inner home-benefit-grid"><article><span>01</span><h3>Personalizzazione completa</h3><p>Scegli colori, caratteri, testi e ordine dei blocchi per creare un invito davvero tuo.</p></article><article><span>02</span><h3>Conferme organizzate</h3><p>Ricevi le partecipazioni e consulta dalla dashboard invitati, allergie e informazioni aggiuntive.</p></article><article><span>03</span><h3>Un link per tutto</h3><p>Programma, countdown, indicazioni stradali, lista desideri e ricordi degli invitati in un unico spazio.</p></article></div></section>

      <section className="section home-template-section"><div className="section-inner home-section-head"><div><p className="eyebrow">Una grafica per ogni occasione</p><h2>Scegli lo stile del tuo evento.</h2></div><div><p className="muted">Matrimoni, compleanni, battesimi, comunioni, lauree ed eventi privati o aziendali. Ogni template è personalizzabile nei colori e nei caratteri.</p><a href="/templates">Guarda tutti i template →</a></div></div><div className="section-inner home-template-grid">{featuredTemplates.map((template) => <a href="/templates" className="home-template-card" key={template.name}><img src={template.image} alt={`Template ${template.name} per ${template.category}`} /><div><span>{template.category}</span><strong>{template.name}</strong></div></a>)}</div></section>

      <section className="section home-how-section" id="come-funziona"><div className="section-inner home-section-head"><div><p className="eyebrow">Come funziona</p><h2>Dal primo dettaglio alla condivisione.</h2></div><p className="muted">Puoi iniziare senza pagare. Costruisci e controlla l’anteprima; scegli il pacchetto soltanto quando sei pronto a pubblicare.</p></div><div className="section-inner home-steps-grid"><article><span>1</span><h3>Scegli il template</h3><p>Trova la grafica più adatta al tuo evento e personalizzala.</p></article><article><span>2</span><h3>Inserisci i contenuti</h3><p>Aggiungi data, luoghi, programma, testi, foto e tutte le informazioni utili.</p></article><article><span>3</span><h3>Scegli il pacchetto</h3><p>Seleziona il numero di invitati e completa il pagamento una tantum.</p></article><article><span>4</span><h3>Condividi l’invito</h3><p>Invia il link e segui conferme e richieste direttamente dalla dashboard.</p></article></div></section>

      <section className="section home-pricing-section"><div className="section-inner"><div className="home-pricing-heading"><p className="eyebrow">Prezzi semplici e trasparenti</p><h2>Scegli il pacchetto in base ai tuoi invitati.</h2><p className="muted">Nessun abbonamento e nessun rinnovo automatico. Crei gratuitamente e paghi una sola volta quando decidi di pubblicare.</p></div><div className="home-pricing-grid"><article><span>Fino a 30 invitati</span><h3>Essenziale</h3><strong>€29</strong><p>Perfetto per feste intime e piccoli eventi.</p></article><article className="recommended"><span>Fino a 100 invitati</span><h3>Completo</h3><strong>€59</strong><p>La scelta ideale per matrimoni ed eventi.</p><small>Più scelto</small></article><article><span>Invitati illimitati</span><h3>Premium</h3><strong>€99</strong><p>Per grandi eventi senza limiti.</p></article></div><div className="home-pricing-footer"><span>Ti servono più posti? Aggiungi 50 invitati a €5.</span><a className="button" href="/abbonamenti">Confronta i pacchetti</a></div></div></section>

      <section className="section home-final-cta"><div className="section-inner"><p className="eyebrow">Il tuo invito, a modo tuo</p><h2>Inizia oggi a creare qualcosa di speciale.</h2><p>Progetta gratuitamente il tuo invito e guarda ogni modifica in tempo reale.</p><div className="actions"><a className="button" href="/registrati">Crea il tuo invito</a><a className="button light" href="/templates">Esplora i template</a></div></div></section>

      <footer className="home-footer"><a className="brand" href="/">ilmioinvito.com</a><p>Inviti digitali personalizzati per i momenti che contano.</p><nav><a href="/templates">Template</a><a href="/abbonamenti">Prezzi</a><a href="/login">Accedi</a><a href="/registrati">Registrati</a></nav></footer>
    </main>
  );
}
