"use client";

import { useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";
import { createClient } from "@/lib/supabase/client";
import { readDrafts, readEditingDraft, saveDraft, setEditingDraft, type InvitationDraft } from "@/lib/draft-storage";
import { saveDraftToSupabase, uploadCoverLogo } from "@/lib/supabase/drafts";

type SupabaseClient = NonNullable<ReturnType<typeof createClient>>;
const DEFAULT_COLOR="#d6ad60";const COLOR_PRESETS=["#d6ad60","#ffffff","#111111","#c7c7c7","#b76e79","#7d2235","#1f5f99","#2f6b4f"];
function currentBuilderTitle(){return typeof document==="undefined"?"":document.querySelector<HTMLInputElement>("#title")?.value.trim()??"";}
function resolveCurrentDraft():InvitationDraft|null{if(typeof window==="undefined")return null;const id=new URLSearchParams(window.location.search).get("edit"),e=readEditingDraft();if(id&&e?.id===id)return e;if(!id&&e){const t=currentBuilderTitle();if(!t||e.title.trim()===t)return e;}const ds=readDrafts();if(id)return ds.find(d=>d.id===id)??null;const t=currentBuilderTitle();return t?ds.find(d=>d.title.trim()===t)??null:null;}
export function CelebrationNumberEditor(){const[target,setTarget]=useState<HTMLElement|null>(null),[previewTarget,setPreviewTarget]=useState<HTMLElement|null>(null),[hasVideo,setHasVideo]=useState(false),[videoDataVisible,setVideoDataVisible]=useState(false),[draft,setDraft]=useState<InvitationDraft|null>(null),[number,setNumber]=useState(""),[color,setColor]=useState(DEFAULT_COLOR),[mode,setMode]=useState<"number"|"logo">("number"),[logoUrl,setLogoUrl]=useState(""),[logoScale,setLogoScale]=useState(1),[message,setMessage]=useState(""),[uploading,setUploading]=useState(false);const supabase=useMemo(()=>createClient(),[]);
 async function findInvitationId(d:InvitationDraft|null,c:SupabaseClient){if(d?.id){const{data}=await c.from("invitations").select("id").eq("id",d.id).maybeSingle();if(data?.id)return data.id as string;}const t=currentBuilderTitle();if(!t)return null;const{data}=await c.from("invitations").select("id").eq("title",t).order("updated_at",{ascending:false}).limit(1).maybeSingle();return(data?.id as string|undefined)??null;}
 async function load(d:InvitationDraft|null,c:SupabaseClient){const id=await findInvitationId(d,c);if(id){const{data}=await c.from("invitation_celebration_number").select("celebration_number, celebration_color").eq("invitation_id",id).maybeSingle();setNumber(data?.celebration_number??"");setColor(data?.celebration_color??DEFAULT_COLOR);}setMode(d?.theme.coverElement??"number");setLogoUrl(d?.theme.coverLogoUrl??"");setLogoScale(d?.theme.coverLogoScale??1);}
 useEffect(()=>{let last="";const sync=()=>{const date=document.querySelector<HTMLInputElement>("#date");if(date?.parentElement)setTarget(date.parentElement.parentElement??date.parentElement);const hero=document.querySelector<HTMLElement>(".phone-hero-preview");if(hero){hero.style.position="relative";setPreviewTarget(hero);setHasVideo(Boolean(hero.querySelector("video")));setVideoDataVisible(Boolean(hero.querySelector(".phone-video-data")));}const cur=resolveCurrentDraft();setDraft(cur);const id=cur?.id??currentBuilderTitle();if(id!==last){last=id;if(supabase)void load(cur,supabase);}};sync();const timer=window.setInterval(sync,300);return()=>window.clearInterval(timer);},[supabase]);
 async function persistTheme(nextMode=mode,nextLogo=logoUrl,nextScale=logoScale){const d=resolveCurrentDraft()??draft;if(!d)return;const next={...d,theme:{...d.theme,coverElement:nextMode,coverLogoUrl:nextLogo,coverLogoScale:nextScale},updatedAt:new Date().toISOString()} as InvitationDraft;setDraft(next);saveDraft(next);setEditingDraft(next);await saveDraftToSupabase(next);}
 useEffect(()=>{const keepCoverAfterSave=(event:MouseEvent)=>{const button=(event.target as HTMLElement).closest("button");if(!button)return;const label=(button.textContent??"").trim();if(!label.includes("Salva bozza")&&!label.includes("Pubblica")&&!label.includes("Aggiorna invito"))return;window.setTimeout(()=>{void persistTheme(mode,logoUrl,logoScale);},1100);};document.addEventListener("click",keepCoverAfterSave,true);return()=>document.removeEventListener("click",keepCoverAfterSave,true);},[mode,logoUrl,logoScale,draft]);
 async function saveNumber(nextNumber=number,nextColor=color){const clean=nextNumber.replace(/[^0-9]/g,"").slice(0,3);setNumber(clean);setColor(nextColor);const c=supabase;if(!c)return;const id=await findInvitationId(draft,c);if(!id){setMessage("Salva prima la bozza dell'invito.");return;}const{error}=await c.from("invitation_celebration_number").upsert({invitation_id:id,celebration_number:clean,celebration_color:nextColor,updated_at:new Date().toISOString()});setMessage(error?error.message:clean?"Numero salvato.":"Numero rimosso.");}
 async function chooseMode(next:"number"|"logo"){setMode(next);setMessage("");await persistTheme(next,logoUrl,logoScale);}
 async function uploadLogo(file?:File){if(!file)return;const d=resolveCurrentDraft()??draft;if(!d){setMessage("Salva prima la bozza.");return;}setUploading(true);const result=await uploadCoverLogo(d.id,file);setUploading(false);if(result.status==="error"){setMessage(result.message);return;}setLogoUrl(result.url);setMode("logo");await persistTheme("logo",result.url,logoScale);setMessage("Logo caricato e salvato.");}
 if(!target)return null;
 const editor=createPortal(<div className="field" style={{marginTop:12}}><label>Elemento copertina</label><div style={{display:"flex",gap:8,margin:"8px 0 12px",flexWrap:"wrap"}}><button className={`button ${mode==="number"?"":"light"}`} type="button" onClick={()=>void chooseMode("number")}>Numero / età</button><button className={`button ${mode==="logo"?"":"light"}`} type="button" onClick={()=>void chooseMode("logo")}>Logo / immagine</button></div>{mode==="number"?<><label htmlFor="celebration-number">Età / Numero</label><input id="celebration-number" inputMode="numeric" maxLength={3} placeholder="Es. 18, 40, 50" value={number} onChange={e=>{setNumber(e.target.value.replace(/[^0-9]/g,"").slice(0,3));setMessage("");}} onBlur={()=>void saveNumber()}/><div style={{marginTop:10}}><label style={{display:"block",marginBottom:7}}>Colore del numero</label><div style={{display:"flex",flexWrap:"wrap",gap:8,alignItems:"center"}}>{COLOR_PRESETS.map(p=><button key={p} type="button" aria-label={`Colore ${p}`} onClick={()=>{setColor(p);void saveNumber(number,p);}} style={{width:30,height:30,borderRadius:"50%",border:color===p?"3px solid #6f3f3f":"1px solid #b9aaa0",background:p,cursor:"pointer"}}/>)}<input type="color" value={color} onChange={e=>setColor(e.target.value)} onBlur={()=>void saveNumber(number,color)}/></div></div></>:<><label>Logo o immagine aziendale</label><label className="button light" style={{cursor:"pointer",display:"inline-flex",marginTop:7}}>{uploading?"Caricamento...":logoUrl?"Cambia logo":"Carica logo"}<input accept="image/jpeg,image/png,image/webp" type="file" disabled={uploading} style={{display:"none"}} onChange={e=>{void uploadLogo(e.currentTarget.files?.[0]);e.currentTarget.value="";}}/></label>{logoUrl?<><div style={{marginTop:12,padding:12,border:"1px solid rgba(63,41,42,.12)",borderRadius:14,textAlign:"center"}}><img src={logoUrl} alt="Logo copertina" style={{maxWidth:180,maxHeight:90,objectFit:"contain"}}/></div><label style={{display:"block",marginTop:12}}>Dimensione logo: {Math.round(logoScale*100)}%</label><input type="range" min="0.5" max="1.5" step="0.05" value={logoScale} onChange={e=>{const s=Number(e.target.value);setLogoScale(s);void persistTheme("logo",logoUrl,s);}}/></>:null}<small style={{display:"block",marginTop:8}}>Consigliato PNG con sfondo trasparente. Massimo 8 MB.</small></>}{message?<small style={{display:"block",marginTop:7}}>{message}</small>:null}</div>,target);
 const visible=!hasVideo||videoDataVisible;const preview=previewTarget&&visible?(mode==="logo"&&logoUrl?createPortal(<div style={{position:"absolute",left:"50%",top:hasVideo?"9%":"calc(-3% + 86px)",transform:"translateX(-50%)",zIndex:20,width:`${Math.round(46*logoScale)}%`,height:100,pointerEvents:"none",display:"flex",alignItems:"center",justifyContent:"center"}}><img src={logoUrl} alt="Logo" style={{width:"100%",height:"100%",objectFit:"contain",display:"block"}}/></div>,previewTarget):number?createPortal(<div style={{position:"absolute",left:"50%",top:hasVideo?"10%":"calc(-3% + 86px)",transform:"translateX(-50%)",zIndex:20,width:"88%",textAlign:"center",pointerEvents:"none",fontFamily:"Georgia, 'Times New Roman', serif",fontWeight:700,fontSize:"clamp(54px, 17vw, 100px)",lineHeight:".82",letterSpacing:"-.05em",color,WebkitTextStroke:"1px rgba(255,255,255,.28)",textShadow:"0 2px 2px rgba(0,0,0,.22), 0 6px 16px rgba(0,0,0,.30)"}}>{number}</div>,previewTarget):null):null;
 return <>{editor}{preview}</>;
}
