"use client";

import { useEffect, useState } from "react";
import { createPortal } from "react-dom";
import { readDrafts, readEditingDraft, saveDraft, setEditingDraft, type InvitationDraft, type InvitationTheme } from "@/lib/draft-storage";
import { saveDraftToSupabase } from "@/lib/supabase/drafts";

type MetaStyle = NonNullable<InvitationTheme["heroMetaStyle"]>;
const options: Array<{ value: MetaStyle; label: string }> = [
  { value: "pills", label: "Pillole" }, { value: "minimal", label: "Minimal" }, { value: "cards", label: "Card eleganti" }, { value: "editorial", label: "Editoriale" }
];
const MIN=.7,MAX=1.8,STEP=.05;
const clamp=(v:number)=>Math.min(MAX,Math.max(MIN,Number(v.toFixed(2))));
function currentDraft(){const editing=readEditingDraft();const editId=new URLSearchParams(window.location.search).get("edit");if(editId&&editing?.id===editId)return editing;const title=document.querySelector<HTMLInputElement>("#title")?.value.trim();return readDrafts().find(d=>d.title.trim()===title)??editing;}
function europeanDate(value:string){const match=/^(\d{4})-(\d{2})-(\d{2})$/.exec(value);return match?`${match[3]}/${match[2]}/${match[1]}`:value;}
function apply(style:MetaStyle,scale:number){const dateValue=document.querySelector<HTMLInputElement>("#date")?.value||currentDraft()?.eventDate||"";document.querySelectorAll<HTMLElement>(".preview-phone .phone-meta").forEach(meta=>{meta.dataset.metaStyle=style;meta.style.setProperty("--hero-meta-scale",String(scale));meta.style.fontSize=`${13*scale}px`;const spans=meta.querySelectorAll<HTMLElement>("span");if(spans[0]){spans[0].textContent=europeanDate(dateValue)||"Data";spans[0].style.fontSize="inherit";}if(spans[1])spans[1].style.display="none";});}
export function HeroMetaStyleEditor(){const[style,setStyle]=useState<MetaStyle>("pills"),[scale,setScale]=useState(1),[target,setTarget]=useState<HTMLElement|null>(null);
 useEffect(()=>{let loadedId="";const setup=()=>{const date=document.querySelector<HTMLInputElement>("#date");const row=date?.closest<HTMLElement>(".field-row")??null;if(row){let mount=row.parentElement?.querySelector<HTMLElement>("[data-hero-meta-style-mount]")??null;if(!mount){mount=document.createElement("div");mount.dataset.heroMetaStyleMount="true";row.insertAdjacentElement("afterend",mount);}setTarget(mount);}const draft=currentDraft();const id=draft?.id??"new";if(id!==loadedId){loadedId=id;const saved=draft?.theme.heroMetaStyle??"pills",savedScale=clamp(draft?.theme.heroMetaScale??1);setStyle(saved);setScale(savedScale);apply(saved,savedScale);}else apply(style,scale);};setup();const timer=window.setInterval(setup,500);const css=document.createElement("style");css.dataset.heroMetaStyle="true";css.textContent=`[data-hero-meta-style-mount]{width:100%}.hero-meta-style-editor{display:grid;gap:10px;margin:10px 0 16px;padding-top:4px}.hero-meta-style-options{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.hero-meta-style-options button{padding:11px 12px;border:1px solid rgba(166,109,112,.32);border-radius:14px;background:#fff;color:#5c383a;font-weight:700}.hero-meta-style-options button.active{background:#a66d70;color:#fff;border-color:#a66d70}.hero-meta-size{display:grid;grid-template-columns:52px minmax(120px,1fr) 52px;gap:10px;align-items:center}.hero-meta-size button{height:38px}.hero-meta-size input{width:100%}.preview-phone .phone-meta{font-size:calc(13px * var(--hero-meta-scale,1))!important}.preview-phone .phone-meta span{font-size:inherit!important}.preview-phone .phone-meta[data-meta-style="minimal"] span{border:0!important;background:transparent!important;border-radius:0!important;padding:3px 8px!important;border-bottom:1px solid currentColor!important}.preview-phone .phone-meta[data-meta-style="cards"] span{border:0!important;border-radius:12px!important;padding:10px 13px!important;background:rgba(255,255,255,.78)!important;box-shadow:0 5px 18px rgba(0,0,0,.10)!important}.preview-phone .phone-meta[data-meta-style="editorial"]{border-top:1px solid currentColor;border-bottom:1px solid currentColor;padding:8px 0!important}.preview-phone .phone-meta[data-meta-style="editorial"] span{border:0!important;border-radius:0!important;background:transparent!important;padding:2px 12px!important}@media(max-width:760px){.hero-meta-style-options{grid-template-columns:1fr}}`;document.head.appendChild(css);return()=>{window.clearInterval(timer);css.remove();};},[style,scale]);
 async function persist(nextStyle:MetaStyle,nextScale:number){const draft=currentDraft();if(!draft)return;const next:InvitationDraft={...draft,eventDate:document.querySelector<HTMLInputElement>("#date")?.value||draft.eventDate,theme:{...draft.theme,heroMetaStyle:nextStyle,heroMetaScale:nextScale},updatedAt:new Date().toISOString()};saveDraft(next);setEditingDraft(next);await saveDraftToSupabase(next);}
 function choose(value:MetaStyle){setStyle(value);apply(value,scale);void persist(value,scale);}function resize(value:number){const next=clamp(value);setScale(next);apply(style,next);void persist(style,next);}
 if(!target)return null;return createPortal(<div className="hero-meta-style-editor"><strong>Grafica data</strong><div className="hero-meta-style-options">{options.map(o=><button className={style===o.value?"active":""} key={o.value} type="button" onClick={()=>choose(o.value)}>{o.label}</button>)}</div><label>Dimensione data: {Math.round(scale*100)}%</label><div className="hero-meta-size"><button type="button" onClick={()=>resize(scale-STEP)}>A−</button><input aria-label="Dimensione data" type="range" min={MIN} max={MAX} step={STEP} value={scale} onChange={e=>resize(Number(e.target.value))}/><button type="button" onClick={()=>resize(scale+STEP)}>A+</button></div></div>,target);
}
