"use client";
import { useEffect,useState } from "react";import{createPortal}from"react-dom";import{readDrafts,readEditingDraft,saveDraft,setEditingDraft,type InvitationDraft,type InvitationTheme}from"@/lib/draft-storage";import{saveDraftToSupabase}from"@/lib/supabase/drafts";
const MIN=.75,MAX=1.8,STEP=.05;const clamp=(v:number)=>Math.min(MAX,Math.max(MIN,Number(v.toFixed(2))));
const fonts:Array<{value:InvitationTheme["fontStyle"];label:string;family:string}>=[{value:"serif",label:"Calligrafico",family:"Georgia,serif"},{value:"script",label:"Corsivo elegante",family:"cursive"},{value:"modern",label:"Moderno",family:"Arial,sans-serif"},{value:"classic",label:"Classico",family:"'Times New Roman',serif"},{value:"elegant",label:"Elegante",family:"Didot,'Times New Roman',serif"},{value:"romantic",label:"Romantico",family:"'Brush Script MT',cursive"},{value:"editorial",label:"Editoriale",family:"Garamond,Georgia,serif"},{value:"minimalist",label:"Minimal",family:"Helvetica,Arial,sans-serif"},{value:"soft",label:"Morbido",family:"Trebuchet MS,Arial,sans-serif"},{value:"bold",label:"Deciso",family:"Arial Black,Arial,sans-serif"}];
function currentDraft():InvitationDraft|null{const id=new URLSearchParams(window.location.search).get("edit"),e=readEditingDraft();if(id&&e?.id===id)return e;const t=document.querySelector<HTMLInputElement>("#title")?.value.trim();return readDrafts().find(d=>d.title.trim()===t)??e;}
export function SplitFontScaleEditor(){const[target,setTarget]=useState<HTMLElement|null>(null),[titleScale,setTitleScale]=useState(1),[heroTitleScale,setHeroTitleScale]=useState(1),[textScale,setTextScale]=useState(1),[font,setFont]=useState<InvitationTheme["fontStyle"]>("serif");
 function apply(a:number,b:number,c:number,f=font){const p=document.querySelector<HTMLElement>(".preview-phone");if(!p)return;p.style.setProperty("--invitation-title-scale",String(a));p.style.setProperty("--hero-title-scale",String(b));p.style.setProperty("--invitation-text-scale",String(c));p.style.setProperty("--invitation-font-family",fonts.find(x=>x.value===f)?.family??fonts[0].family);}
 async function persist(a:number,b:number,c:number,f=font){const d=currentDraft();if(!d)return;const n={...d,theme:{...d.theme,fontScale:1,titleFontScale:a,heroTitleScale:b,textFontScale:c,fontStyle:f},updatedAt:new Date().toISOString()}as InvitationDraft;saveDraft(n);setEditingDraft(n);await saveDraftToSupabase(n);}
 function change(kind:"titles"|"hero"|"texts",v:number){const n=clamp(v),a=kind==="titles"?n:titleScale,b=kind==="hero"?n:heroTitleScale,c=kind==="texts"?n:textScale;if(kind==="titles")setTitleScale(n);if(kind==="hero")setHeroTitleScale(n);if(kind==="texts")setTextScale(n);apply(a,b,c);void persist(a,b,c);}
 useEffect(()=>{const find=()=>{const labels=Array.from(document.querySelectorAll<HTMLLabelElement>(".field label"));const old=labels.find(l=>l.textContent?.includes("Dimensione testi:"));const field=old?.closest<HTMLElement>(".field");if(!field)return;field.style.display="none";if(field.parentElement)setTarget(field.parentElement);const d=currentDraft(),fallback=d?.theme.fontScale??1,a=clamp(d?.theme.titleFontScale??fallback),b=clamp(d?.theme.heroTitleScale??d?.theme.titleFontScale??fallback),c=clamp(d?.theme.textFontScale??fallback),f=d?.theme.fontStyle??"serif";setTitleScale(a);setHeroTitleScale(b);setTextScale(c);setFont(f);apply(a,b,c,f);};find();const timer=window.setInterval(find,700);const s=document.createElement("style");s.textContent=`.preview-phone{font-family:var(--invitation-font-family)!important}.preview-phone .phone-hero-preview h2{font-size:calc(30px * var(--hero-title-scale,1))!important;font-family:var(--invitation-font-family)!important}.preview-phone .phone-featured-text,.preview-phone .phone-location strong,.preview-phone .phone-social-heading strong{font-size:calc(30px * var(--invitation-title-scale,1))!important;font-family:var(--invitation-font-family)!important}.preview-phone .phone-hero-preview p,.preview-phone .phone-slot p,.preview-phone .phone-location,.preview-phone .phone-program-item strong,.preview-phone .phone-program-item span,.preview-phone .phone-social-heading small{font-size:calc(13px * var(--invitation-text-scale,1))!important}.split-font-scale-grid{display:grid;grid-template-columns:1fr;gap:14px;width:100%}.font-size-control{display:grid;grid-template-columns:52px minmax(120px,1fr) 52px;gap:10px;align-items:center}.font-size-control input{width:100%}.font-size-control button{width:52px}`;document.head.appendChild(s);return()=>{window.clearInterval(timer);s.remove();};},[]);
 if(!target)return null;const control=(label:string,value:number,kind:"titles"|"hero"|"texts")=><div className="field"><label>{label}: {Math.round(value*100)}%</label><div className="font-size-control"><button type="button" onClick={()=>change(kind,value-STEP)}>A−</button><input type="range" min={MIN} max={MAX} step={STEP} value={value} onChange={e=>change(kind,Number(e.target.value))}/><button type="button" onClick={()=>change(kind,value+STEP)}>A+</button></div></div>;
 return createPortal(<div className="split-font-scale-grid"><div className="field"><label>Stile font</label><select value={font} onChange={e=>{const f=e.target.value as InvitationTheme["fontStyle"];setFont(f);apply(titleScale,heroTitleScale,textScale,f);void persist(titleScale,heroTitleScale,textScale,f);}}>{fonts.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></div>{control("Dimensione titoli sezioni",titleScale,"titles")}{control("Dimensione titolo invito",heroTitleScale,"hero")}{control("Dimensione testi",textScale,"texts")}</div>,target);}
