"use client";

import { useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";
import type { CSSProperties } from "react";
import { createClient } from "@/lib/supabase/client";
import { readDrafts, readEditingDraft, type InvitationDraft } from "@/lib/draft-storage";

type StoryMedia = { id: string; invitation_id: string; image_url: string; caption: string | null; sort_order: number; };
const panelStyle: CSSProperties = { marginTop: "14px", padding: "18px", borderRadius: "18px", border: "1px solid rgba(63,41,42,.12)", background: "rgba(255,255,255,.72)" };
const gridStyle: CSSProperties = { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(160px,1fr))", gap: "12px", marginTop: "14px" };
function currentBuilderTitle() { if (typeof document === "undefined") return ""; return document.querySelector<HTMLInputElement>("#title")?.value.trim() ?? ""; }
function resolveCurrentDraft(): InvitationDraft | null { if(typeof window==="undefined")return null;const editingId=new URLSearchParams(window.location.search).get("edit");const editingDraft=readEditingDraft();if(editingId&&editingDraft?.id===editingId)return editingDraft;if(!editingId&&editingDraft){const t=currentBuilderTitle();if(!t||editingDraft.title.trim()===t)return editingDraft;}const drafts=readDrafts();if(editingId)return drafts.find(d=>d.id===editingId)??null;const title=currentBuilderTitle();return title?drafts.find(d=>d.title.trim()===title)??null:null; }
export function StoryEditor(){
 const[draft,setDraft]=useState<InvitationDraft|null>(null),[storyTitle,setStoryTitle]=useState("La nostra storia"),[storyText,setStoryText]=useState(""),[media,setMedia]=useState<StoryMedia[]>([]),[message,setMessage]=useState(""),[uploading,setUploading]=useState(false),[titleTarget,setTitleTarget]=useState<HTMLElement|null>(null),[mediaTarget,setMediaTarget]=useState<HTMLElement|null>(null),[previewTarget,setPreviewTarget]=useState<HTMLElement|null>(null);const supabase=useMemo(()=>createClient(),[]);
 async function findInvitationId(d:InvitationDraft|null){const c=supabase;if(!c)return null;if(d?.id){const{data}=await c.from("invitations").select("id").eq("id",d.id).maybeSingle();if(data?.id)return data.id as string;}const title=currentBuilderTitle();if(!title)return null;const{data}=await c.from("invitations").select("id").eq("title",title).order("updated_at",{ascending:false}).limit(1).maybeSingle();return(data?.id as string|undefined)??null;}
 async function loadStory(d:InvitationDraft|null){const c=supabase;if(!c)return;const id=await findInvitationId(d);if(!id){setMedia([]);return;}const[{data:content},{data:rows,error}]=await Promise.all([c.from("invitation_content").select("story_title").eq("invitation_id",id).maybeSingle(),c.from("invitation_story_media").select("id, invitation_id, image_url, caption, sort_order").eq("invitation_id",id).order("sort_order",{ascending:true}).order("created_at",{ascending:true})]);if(error){setMessage(error.message);return;}setStoryTitle(content?.story_title||"La nostra storia");setMedia((rows??[])as StoryMedia[]);}
 useEffect(()=>{let last="";const sync=()=>{const ta=document.querySelector<HTMLTextAreaElement>("#story");const label=document.querySelector<HTMLLabelElement>('label[for="story"]');if(label)label.textContent="Racconto della storia";if(ta?.parentElement){setStoryText(ta.value);let top=ta.parentElement.querySelector<HTMLElement>("[data-story-title-mount]");if(!top){top=document.createElement("div");top.dataset.storyTitleMount="true";ta.parentElement.insertBefore(top,label??ta);}setTitleTarget(top);let bottom=ta.parentElement.querySelector<HTMLElement>("[data-story-media-mount]");if(!bottom){bottom=document.createElement("div");bottom.dataset.storyMediaMount="true";ta.insertAdjacentElement("afterend",bottom);}setMediaTarget(bottom);}const hero=document.querySelector<HTMLElement>(".phone-hero-preview");if(hero?.parentElement){let m=hero.parentElement.querySelector<HTMLElement>("[data-story-preview-mount]");if(!m){m=document.createElement("div");m.dataset.storyPreviewMount="true";hero.insertAdjacentElement("afterend",m);}setPreviewTarget(m);}const cur=resolveCurrentDraft();setDraft(cur);const id=cur?.id??currentBuilderTitle();if(id!==last){last=id;void loadStory(cur);}};sync();const timer=window.setInterval(sync,500);return()=>window.clearInterval(timer);},[]);
 async function saveTitle(v=storyTitle){const c=supabase;if(!c)return;const id=await findInvitationId(draft);if(!id){setMessage("Prima premi Salva bozza nel builder.");return;}const clean=v.trim()||"La nostra storia";const{error}=await c.from("invitation_content").update({story_title:clean,updated_at:new Date().toISOString()}).eq("invitation_id",id);setStoryTitle(clean);setMessage(error?error.message:"Titolo della storia salvato.");}
 async function uploadPhoto(file?:File){const c=supabase;if(!file||!c)return;if(!file.type.startsWith("image/")){setMessage("Seleziona un file immagine.");return;}if(file.size>8*1024*1024){setMessage("La foto non può superare 8 MB.");return;}setUploading(true);try{const{data:u}=await c.auth.getUser();if(!u.user){setMessage("Accedi prima di caricare le foto.");return;}const id=await findInvitationId(draft);if(!id){setMessage("Prima premi Salva bozza nel builder.");return;}const ext=(file.name.split(".").pop()||"jpg").toLowerCase().replace(/[^a-z0-9]/g,"");const path=`${u.user.id}/${id}/${crypto.randomUUID()}.${ext}`;const{error:ue}=await c.storage.from("invitation-story-images").upload(path,file,{cacheControl:"3600",upsert:false,contentType:file.type});if(ue){setMessage(ue.message);return;}const{data:url}=c.storage.from("invitation-story-images").getPublicUrl(path);const{error:ie}=await c.from("invitation_story_media").insert({invitation_id:id,image_url:url.publicUrl,caption:"",sort_order:media.length});if(ie){setMessage(ie.message);return;}await loadStory(draft);}finally{setUploading(false);}}
 async function updateCaption(item:StoryMedia,caption:string){const c=supabase;if(!c)return;setMedia(x=>x.map(r=>r.id===item.id?{...r,caption}:r));await c.from("invitation_story_media").update({caption,updated_at:new Date().toISOString()}).eq("id",item.id);}
 async function removePhoto(item:StoryMedia){const c=supabase;if(!c)return;await c.from("invitation_story_media").delete().eq("id",item.id);await loadStory(draft);}
 if(!titleTarget)return null;
 const titleEditor=createPortal(<section style={panelStyle}><h3 style={{margin:"0 0 6px",fontSize:18}}>Personalizza la storia</h3><p className="muted" style={{margin:"0 0 14px"}}>Scegli il titolo della sezione e aggiungi le fotografie che accompagneranno il racconto.</p><div className="field"><label htmlFor="story-title-custom">Titolo della sezione</label><div style={{display:"flex",gap:8,flexWrap:"wrap",margin:"7px 0 9px"}}><button className="button light" type="button" onClick={()=>void saveTitle("La nostra storia")}>La nostra storia</button><button className="button light" type="button" onClick={()=>void saveTitle("La mia storia")}>La mia storia</button></div><input id="story-title-custom" value={storyTitle} onChange={e=>setStoryTitle(e.target.value)} onBlur={()=>void saveTitle()}/><button className="button light" type="button" style={{marginTop:8,width:"100%"}} onClick={()=>void saveTitle()}>Salva titolo</button></div></section>,titleTarget);
 const photos=mediaTarget?createPortal(<div style={{marginTop:16}}><strong>Fotografie della storia</strong><p className="muted" style={{margin:"4px 0 10px"}}>Puoi aggiungere immagini fino a 8 MB e una didascalia per ciascuna.</p><label className="button light" style={{cursor:uploading?"wait":"pointer"}}>{uploading?"Caricamento...":"+ Aggiungi foto"}<input accept="image/*" disabled={uploading} type="file" style={{display:"none"}} onChange={e=>{const f=e.currentTarget.files?.[0];void uploadPhoto(f);e.currentTarget.value="";}}/></label>{media.length>0?<div style={gridStyle}>{media.map(item=><article key={item.id} style={{border:"1px solid rgba(63,41,42,.12)",borderRadius:16,overflow:"hidden",background:"#fff"}}><img src={item.image_url} alt={item.caption||"Foto della storia"} style={{width:"100%",aspectRatio:"4 / 3",objectFit:"cover",display:"block"}}/><div style={{padding:10}}><textarea placeholder="Scrivi qui un ricordo, una frase o una breve descrizione della foto..." value={item.caption??""} onChange={e=>void updateCaption(item,e.target.value)} style={{width:"100%",minHeight:92,resize:"vertical"}}/><button className="editor-remove-button" type="button" style={{marginTop:8}} onClick={()=>void removePhoto(item)}>Rimuovi foto</button></div></article>)}</div>:null}{message?<p className="muted">{message}</p>:null}</div>,mediaTarget):null;
 const preview=previewTarget?createPortal(<section className="phone-slot" data-preview-section="story" style={{textAlign:"center"}}><strong className="phone-featured-text" style={{display:"block",marginBottom:8}}>{storyTitle}</strong>{storyText?<p style={{whiteSpace:"pre-wrap"}}>{storyText}</p>:null}{media.length>0?<div style={{display:"grid",gap:10,marginTop:12}}>{media.map(item=><figure key={item.id} style={{margin:0}}><img src={item.image_url} alt={item.caption||"Foto della storia"} style={{width:"100%",borderRadius:14,display:"block",objectFit:"cover"}}/>{item.caption?<figcaption style={{marginTop:6,fontSize:12}}>{item.caption}</figcaption>:null}</figure>)}</div>:null}</section>,previewTarget):null;
 return <>{titleEditor}{photos}{preview}</>;
}
