"use client";

import { useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";
import type { CSSProperties } from "react";
import { createClient } from "@/lib/supabase/client";
import { readDrafts, readEditingDraft, type InvitationDraft } from "@/lib/draft-storage";

type StoryMedia = { id: string; invitation_id: string; image_url: string; caption: string | null; sort_order: number; };
const panelStyle: CSSProperties = { marginTop: "14px", padding: "18px", borderRadius: "18px", border: "1px solid rgba(63,41,42,.12)", background: "rgba(255,255,255,.72)" };
const gridStyle: CSSProperties = { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(160px,1fr))", gap: "12px", marginTop: "14px" };
function currentBuilderTitle() { if (typeof document === "undefined") return ""; return document.querySelector<HTMLInputElement>("#title")?.value.trim() ?? ""; }
function resolveCurrentDraft(): InvitationDraft | null {
  if (typeof window === "undefined") return null;
  const editingId = new URLSearchParams(window.location.search).get("edit"); const editingDraft = readEditingDraft();
  if (editingId && editingDraft?.id === editingId) return editingDraft;
  if (!editingId && editingDraft) { const currentTitle = currentBuilderTitle(); if (!currentTitle || editingDraft.title.trim() === currentTitle) return editingDraft; }
  const drafts = readDrafts(); if (editingId) return drafts.find((draft) => draft.id === editingId) ?? null;
  const title = currentBuilderTitle(); if (!title) return null; return drafts.find((draft) => draft.title.trim() === title) ?? null;
}
export function StoryEditor() {
  const [draft,setDraft]=useState<InvitationDraft|null>(null); const [storyTitle,setStoryTitle]=useState("La nostra storia"); const [storyText,setStoryText]=useState(""); const [media,setMedia]=useState<StoryMedia[]>([]); const [message,setMessage]=useState(""); const [uploading,setUploading]=useState(false); const [target,setTarget]=useState<HTMLElement|null>(null); const [previewTarget,setPreviewTarget]=useState<HTMLElement|null>(null); const supabase=useMemo(()=>createClient(),[]);
  async function findInvitationId(currentDraft: InvitationDraft|null) { const client=supabase; if(!client)return null; if(currentDraft?.id){const{data}=await client.from("invitations").select("id").eq("id",currentDraft.id).maybeSingle();if(data?.id)return data.id as string;} const title=currentBuilderTitle();if(!title)return null;const{data}=await client.from("invitations").select("id").eq("title",title).order("updated_at",{ascending:false}).limit(1).maybeSingle();return(data?.id as string|undefined)??null; }
  async function loadStory(currentDraft: InvitationDraft|null){const client=supabase;if(!client){setMedia([]);return;}const invitationId=await findInvitationId(currentDraft);if(!invitationId){setMedia([]);setMessage("Salva prima la bozza dell'invito. Dopo il salvataggio potrai aggiungere titolo e foto alla storia.");return;}const[{data:content},{data:rows,error}]=await Promise.all([client.from("invitation_content").select("story_title").eq("invitation_id",invitationId).maybeSingle(),client.from("invitation_story_media").select("id, invitation_id, image_url, caption, sort_order").eq("invitation_id",invitationId).order("sort_order",{ascending:true}).order("created_at",{ascending:true})]);if(error){setMessage(error.message);return;}setStoryTitle(content?.story_title||"La nostra storia");setMedia((rows??[])as StoryMedia[]);setMessage("");}
  useEffect(()=>{let lastDraftId="";const sync=()=>{const storyTextarea=document.querySelector<HTMLTextAreaElement>("#story");const label=document.querySelector<HTMLLabelElement>('label[for="story"]');if(label)label.textContent="La nostra storia / La mia storia";if(storyTextarea?.parentElement){setTarget(storyTextarea.parentElement);setStoryText(storyTextarea.value);let helper=storyTextarea.parentElement.querySelector<HTMLElement>("[data-story-field-helper]");if(!helper){helper=document.createElement("small");helper.dataset.storyFieldHelper="true";helper.textContent="Scrivi qui sotto il titolo il racconto della vostra / tua storia.";helper.style.display="block";helper.style.margin="6px 0 8px";helper.style.opacity=".72";storyTextarea.insertAdjacentElement("beforebegin",helper);}}const hero=document.querySelector<HTMLElement>(".phone-hero-preview");if(hero?.parentElement){let mount=hero.parentElement.querySelector<HTMLElement>("[data-story-preview-mount]");if(!mount){mount=document.createElement("div");mount.dataset.storyPreviewMount="true";hero.insertAdjacentElement("afterend",mount);}setPreviewTarget(mount);}const current=resolveCurrentDraft();setDraft(current);const nextId=current?.id??currentBuilderTitle();if(nextId!==lastDraftId){lastDraftId=nextId;void loadStory(current);}};sync();const timer=window.setInterval(sync,500);window.addEventListener("focus",sync);return()=>{window.clearInterval(timer);window.removeEventListener("focus",sync);};},[]);
  async function saveTitle(value=storyTitle){const client=supabase;if(!client){setMessage("Servizio di salvataggio non disponibile.");return;}const invitationId=await findInvitationId(draft);if(!invitationId){setMessage("Prima premi Salva bozza nel builder.");return;}const cleanTitle=value.trim()||"La nostra storia";const{error}=await client.from("invitation_content").update({story_title:cleanTitle,updated_at:new Date().toISOString()}).eq("invitation_id",invitationId);setStoryTitle(cleanTitle);setMessage(error?error.message:"Titolo della storia salvato.");}
  async function uploadPhoto(file?:File){const client=supabase;if(!file){setMessage("Nessuna foto selezionata.");return;}if(!client){setMessage("Servizio di caricamento non disponibile.");return;}if(!file.type.startsWith("image/")){setMessage("Seleziona un file immagine.");return;}if(file.size>8*1024*1024){setMessage("La foto non può superare 8 MB.");return;}setUploading(true);setMessage("Caricamento foto della storia...");try{const{data:userData}=await client.auth.getUser();if(!userData.user){setMessage("Accedi prima di caricare le foto.");return;}const invitationId=await findInvitationId(draft);if(!invitationId){setMessage("Prima premi Salva bozza nel builder, poi riprova ad aggiungere la foto.");return;}const rawExtension=file.name.includes(".")?file.name.split(".").pop():"jpg";const extension=rawExtension?.toLowerCase().replace(/[^a-z0-9]/g,"")||"jpg";const path=`${userData.user.id}/${invitationId}/${crypto.randomUUID()}.${extension}`;const{error:uploadError}=await client.storage.from("invitation-story-images").upload(path,file,{cacheControl:"3600",upsert:false,contentType:file.type||undefined});if(uploadError){setMessage(`Errore caricamento foto: ${uploadError.message}`);return;}const{data:publicUrl}=client.storage.from("invitation-story-images").getPublicUrl(path);const{error:insertError}=await client.from("invitation_story_media").insert({invitation_id:invitationId,image_url:publicUrl.publicUrl,caption:"",sort_order:media.length});if(insertError){await client.storage.from("invitation-story-images").remove([path]);setMessage(`Errore salvataggio foto: ${insertError.message}`);return;}setMessage("Foto aggiunta alla storia.");await loadStory(draft);}catch(error){setMessage(error instanceof Error?`Errore caricamento: ${error.message}`:"Errore imprevisto durante il caricamento della foto.");}finally{setUploading(false);}}
  async function updateCaption(item:StoryMedia,caption:string){const client=supabase;if(!client)return;setMedia(current=>current.map(row=>row.id===item.id?{...row,caption}:row));const{error}=await client.from("invitation_story_media").update({caption,updated_at:new Date().toISOString()}).eq("id",item.id);if(error)setMessage(error.message);}
  async function removePhoto(item:StoryMedia){const client=supabase;if(!client)return;const{error}=await client.from("invitation_story_media").delete().eq("id",item.id);if(error){setMessage(error.message);return;}setMessage("Foto rimossa dalla storia.");await loadStory(draft);}
  if(!target)return null;
  const editor=(<section style={panelStyle} aria-labelledby="story-editor-title"><h3 id="story-editor-title" style={{margin:"0 0 6px",fontSize:"18px"}}>Personalizza la storia</h3><p className="muted" style={{margin:"0 0 14px"}}>Scegli il titolo della sezione e aggiungi le fotografie che accompagneranno il racconto.</p><div className="field"><label htmlFor="story-title-custom">Titolo della sezione</label><input id="story-title-custom" value={storyTitle} onChange={e=>setStoryTitle(e.target.value)} onBlur={()=>void saveTitle()}/><div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:8}}><button className="button light" type="button" onClick={()=>void saveTitle("La nostra storia")}>La nostra storia</button><button className="button light" type="button" onClick={()=>void saveTitle("La mia storia")}>La mia storia</button><button className="button light" type="button" onClick={()=>void saveTitle()}>Salva titolo</button></div></div><div style={{marginTop:16}}><strong>Fotografie della storia</strong><p className="muted" style={{margin:"4px 0 10px"}}>Puoi aggiungere immagini fino a 8 MB e una didascalia per ciascuna.</p><label className="button light" style={{cursor:uploading?"wait":"pointer"}}>{uploading?"Caricamento...":"+ Aggiungi foto"}<input accept="image/*" disabled={uploading} type="file" style={{display:"none"}} onChange={e=>{const selectedFile=e.currentTarget.files?.[0];void uploadPhoto(selectedFile);e.currentTarget.value="";}}/></label></div>{media.length>0?<div style={gridStyle}>{media.map(item=><article key={item.id} style={{border:"1px solid rgba(63,41,42,.12)",borderRadius:16,overflow:"hidden",background:"#fff"}}><img src={item.image_url} alt={item.caption||"Foto della storia"} style={{width:"100%",aspectRatio:"4 / 3",objectFit:"cover",display:"block"}}/><div style={{padding:10}}><textarea aria-label="Didascalia foto" placeholder="Scrivi qui un ricordo, una frase o una breve descrizione della foto..." value={item.caption??""} onChange={e=>void updateCaption(item,e.target.value)} style={{width:"100%",minHeight:92,resize:"vertical"}}/><button className="editor-remove-button" type="button" style={{marginTop:8}} onClick={()=>void removePhoto(item)}>Rimuovi foto</button></div></article>)}</div>:null}{message?<p className="muted" style={{margin:"12px 0 0"}}>{message}</p>:null}</section>);
  const preview=previewTarget?createPortal(<section className="phone-slot" data-preview-section="story" style={{textAlign:"center"}}><strong className="phone-featured-text" style={{display:"block",marginBottom:8}}>{storyTitle}</strong>{storyText?<p style={{whiteSpace:"pre-wrap"}}>{storyText}</p>:null}{media.length>0?<div style={{display:"grid",gap:10,marginTop:12}}>{media.map(item=><figure key={item.id} style={{margin:0}}><img src={item.image_url} alt={item.caption||"Foto della storia"} style={{width:"100%",borderRadius:14,display:"block",objectFit:"cover"}}/>{item.caption?<figcaption style={{marginTop:6,fontSize:12,lineHeight:1.4}}>{item.caption}</figcaption>:null}</figure>)}</div>:null}</section>,previewTarget):null;
  return <>{createPortal(editor,target)}{preview}</>;
}
